### ISSUE TITLE
Tag input

### ISSUE THREAD

**Issue by luiztauffer** [Tauffer-Consulting/dash-cool-components#3]
- [x] Add component for tag input
- [x] Include example in README components list
- [x] Change component name to TagInput
- [x] Write to component (update its values from the backend)
- [x] Include documentation

**Comment by vinicvaz** [comment]
Write to componente:
- When value prop change, re-render tag component updating its state to new tag values

**Comment by vinicvaz** [comment]
When injectedTags > 1, if user deletes a tag, all tags are cleaned.
We have to fix this to delete single tag when the tags are injected automatically.
@raulrozza
